app/urls.py
from django.urls import path,include
from .views import index,detail,create_product,delete_product,update_product,create_order,create_comment,contact_view

app_name = 'app'

urlpatterns = [
    path('',index,name='index'),
    path('category/<int:category_id>',index,name='products_of_category'),
    path('detail/<int:product_id>',detail,name='detail'),
    path('create/',create_product,name='create'),
    path('delete/<int:pk>',delete_product,name='delete'),
    path('update/<int:pk>',update_product,name='update'),
    path('detail/<int:pk>/orders/',create_order,name='create_order'),
    path('detail/<int:product_id>/comments',create_comment,name='create_comment'),
    path('contact/',contact_view,name='contact_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',include('app.urls',namespace='app')),
#     path('user/',include('user.urls',namespace='user'))
    
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('user/', include('user.urls', namespace='user')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from .views import login_page,logout_page,register_page


app_name = 'user'

urlpatterns = [
    path('login/',login_page,name='login_page'),
    path('logout/',logout_page,name='logout_page'),
    path('register/',register_page,name='register_page'),
]



'''
http://127.0.0.1:8000/user/login

'''

app/templates/app/base/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="{% static 'app/css/styles.css'  %}" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'app:index'%}">{% trans "Online Shop" %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'app:index' %}">{% trans "Home" %}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:contact_view' %}">{% trans "Get In Touch" %}</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{% trans "Categories" %}</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'app:index' %}">{% trans "All Products" %}</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories %}
                                    <li><a class="dropdown-item" href="{% url 'app:products_of_category' category.id %} ">{{ category.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" action="{% url 'app:index' %}">
                        <input type="text" name="q" class="form-contro">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-search-fill me-1"></i>
                            {% trans "Search" %}
                        </button>
                    </form>
                    {% if user.is_authenticated %}
                        <div>
                            <form method="post" action="{% url 'user:logout_page' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary ms-4">{% trans "Logout" %}</button>
                            </form>
                        </div>
                    {% else %}
                        <div>
                            <a href="{% url 'user:login_page' %}">
                                <button type="button" class="btn btn-primary ms-4">{% trans "Login" %}</button>
                            </a>
                        </div>
                    {% endif %}
                    <form action="/i18n/setlang/" method="post" class="ms-3">
                        {% csrf_token %}
                        <select name="language" onchange="this.form.submit()" class="form-select">
                            <option value="uz" {% if LANGUAGE_CODE == 'uz' %}selected{% endif %}>{% trans "Uzbek" %}</option>
                            <option value="ru" {% if LANGUAGE_CODE == 'ru' %}selected{% endif %}>{% trans "Russian" %}</option>
                            <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>{% trans "English" %}</option>
                        </select>
                    </form>
                </div>
            </div>
        </nav>
       
        {% block home_content %}{% endblock %}
        {% block detail_content %}{% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">{% trans "Copyright" %} &copy; {% trans "Your Website 2023" %}</p>
            </div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'app/js/scripts.js' %}"></script>

    </body>
</html>